### ISSUE TITLE
本地首次运行初始化数据库报错

### ISSUE THREAD

**Issue by ddgth** [mizhexiaoxiao/vue-fastapi-admin#47]
Linux环境 python3.11 已安装 tortoise-orm[asyncmy]
配置的是mariadb数据库，首次运行报错。 对于aerich不太了解，麻烦帮忙看下是哪里的问题。
报错内容如下：
```
INFO:     Will watch for changes in these directories: ['/root/hostmonit']
INFO:     Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
INFO:     Started reloader process [29446] using WatchFiles
INFO:     Started server process [29448]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/root/hostmonit/venv/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/hostmonit/app/__init__.py", line 22, in lifespan
    await init_data()
  File "/root/hostmonit/app/core/init_app.py", line 218, in init_data
    await init_db()
  File "/root/hostmonit/app/core/init_app.py", line 188, in init_db
    await command.migrate()
  File "/root/hostmonit/venv/lib/python3.11/site-packages/aerich/__init__.py", line 127, in migrate
    return await Migrate.migrate(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/hostmonit/venv/lib/python3.11/site-packages/aerich/migrate.py", line 140, in migrate
    cls.diff_models(cls._last_version_content, new_version_content)
  File "/root/hostmonit/venv/lib/python3.11/site-packages/aerich/migrate.py", line 193, in diff_models
    old_models.pop(_aerich, None)
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'po
```

**Comment by ddgth** [comment]
> 不必理会可以正常运行，后续会优化

问题是后续直接就退出程序了，脚本也没有初始化成功。

**Comment by mizhexiaoxiao** [comment]
> > 不必理会可以正常运行，后续会优化
> 
> 问题是后续直接就退出程序了，脚本也没有初始化成功。

删除本地的migrations文件夹已经数据库中的aerich表再重启试试

**Comment by ddgth** [comment]
> > > 不必理会可以正常运行，后续会优化
> > 
> > 
> > 问题是后续直接就退出程序了，脚本也没有初始化成功。
> 
> 删除本地的migrations文件夹已经数据库中的aerich表再重启试试

本地还没有生成migrations文件夹，刚刚建的数据库里面是空的，没有aerich表。

**Comment by ddgth** [comment]
> > > 不必理会可以正常运行，后续会优化
> > 
> > 
> > 问题是后续直接就退出程序了，脚本也没有初始化成功。
> 
> 删除本地的migrations文件夹已经数据库中的aerich表再重启试试

实在抱歉 是我没仔细看，本地是有migrations文件夹的。 删除之后重新运行可以了。非常感谢。
