### ISSUE TITLE
使用myql8作为数据源报错

### ISSUE THREAD

**Issue by kotlef** [mizhexiaoxiao/vue-fastapi-admin#51]
"mysql": {
                "engine": "tortoise.backends.mysql",
                "credentials": {
                    "host": "localhost",  # Database host address
                    "port": 3306,  # Database port
                    "user": "root",  # Database username
                    "password": "",  # Database password
                    "database": "es",  # Database name
                },
            }
            
            ERROR:    Traceback (most recent call last):
  File "/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/vue-fastapi-admin/app/__init__.py", line 22, in lifespan
    await init_data()
  File "/vue-fastapi-admin/app/core/init_app.py", line 219, in init_data
    await init_db()
  File "/vue-fastapi-admin/app/core/init_app.py", line 189, in init_db
    await command.migrate()
  File "/python3.11/site-packages/aerich/__init__.py", line 127, in migrate
    return await Migrate.migrate(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python3.11/site-packages/aerich/migrate.py", line 140, in migrate
    cls.diff_models(cls._last_version_content, new_version_content)
  File "python3.11/site-packages/aerich/migrate.py", line 193, in diff_models
    old_models.pop(_aerich, None)
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by mizhexiaoxiao** [comment]
已修复，拉一下最新代码
